Cleaned up README
shobrook/syntaxis pull request #2
Opened 2018-07-08 15:57 UTC by alichtman

+ Referenced AST before defining the acronym.
+ Syntax highlighting and rephrasing where needed.
+ Grammar stuff
+ Added link to CONTRIBUTING guide that needs to be created.

2018-07-08 20:01 UTC, shobrook commented on README.md
> +  * Searching for nodes by `type`, `id`, `attribute`, or `scope`
These don't need syntax highlighting, they're not part of any syntax.

2018-07-08 20:04 UTC, shobrook commented on README.md
> +`saplings` is a simple library for searching, analyzing, and transforming [ASTs (abstract syntax trees.)](https://en.wikipedia.org/wiki/Abstract_syntax_tree) It provides some generic algorithms (`sap
This is incorrect. When you use an acronym for the first time, it should be used after the words are spelled out. See: https://english.stackexchange.com/questions/36722/how-to-use-fully-qualified-acronyms

2018-07-08 20:05 UTC, shobrook commented on README.md
> +  * Generating `frequency maps` for specific nodes
Yep, again this isn't part of any programming syntax.

2018-07-08 20:05 UTC, shobrook commented on README.md
> +Requires `Python 3.0` or higher.
Not sure the highlighting is necessary.

2018-07-08 20:07 UTC, shobrook commented on README.md
> +## Contributing a Sapling
Sounds a little weird. Idk which one to go with.

2018-07-08 20:09 UTC, shobrook commented on README.md
> +Requires `Python 3.0` or higher.
Not sure the highlighting is necessary.

2018-07-08 20:09 UTC, shobrook requested changes
See comments.

2018-07-08 22:27 UTC, alichtman commented on README.md
> +  * Generating `frequency maps` for specific nodes
I use this for emphasis, not programming syntax. You could bold it, instead, but I think this looks the best, imo.

2018-07-13 03:23 UTC, shobrook approved these changes

2018-07-13 03:23 UTC, merged